formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: WARNING
    stream: ext://sys.stdout
  file:
    backupCount: 6
    class: logginghandlers.timedrotatingfilesmtphandler.TimedRotatingFileSMTPHandler
    configfilename: config.ini
    filename: log/alarmmonitor.log
    formatter: simple
    level: INFO
    send_log: false
    when: midnight
root:
  handlers:
    - console
    - file
  level: DEBUG
version: 1
